### ISSUE TITLE
連打すると白いウィンドウが見え隠れする。

### ISSUE THREAD

**Issue by b4h0-c4t** [uehara1414/bakuretsu-mahou#2]
Mac OS X Sierraにて確認
連打すると、5click/sec程度の速度を超えたあたりから超えた回数分白いウィンドウが0.2秒ほど表示される。
あと重いのもなんとかしてほしいな

**Comment by uehara1414** [comment]
12月の終わり頃に動画素材が提供される予定なので、その時に対処します。
